title: "Performance Predictions in TB-HIV" 
# show_downloads: true 
description: by <a href="https://reevafaisal.github.io/">Reeva Faisal</a>
# logo: "Screenshot 2024-10-13 at 4.04.46 PM_batcheditor_fotor.jpg" 
github_button: true
# email: reevaf@umich.edu
# repository: https://github.com/reevafaisal/reevafaisal.github.io
# theme: jekyll-theme-minima
favicon: true 
plugins:  
  - jekyll-remote-theme 
  
# plugins:
#   - jekyll-sitemap  
#   - jekyll-seo-tag
#   - jemoji
# color-scheme: light

# { scroll: false, shallow: true }
# includes:
#   - assets/js/custom.js

remote_theme: reevafaisal/jekyll-theme-minimal-new
# platforms:
#   - name: GitHub
#     icon: <i class="fa-brands fa-github"></i>
#     link: https://github.com/reevafaisal
#   - name: LinkedIn
#     icon: <i class="fa-brands fa-linkedin"></i>
#     link: https://www.linkedin.com/in/reeva-faisal/
 # - name: Email 
 #    icon: "<img src='https://img.icons8.com/ios-glyphs/30/000000/new-post.png' alt='Email Icon' style='width: 20px; height: 20px;'>"
 #    link: "mailto:reevaf@umich.com"
# editor.find.cursorMoveOnType: false
navigation:
  - name: Introduction
    link: ./index.html#introduction
  - name: Data Cleaning and Exploratory Data Analysis
    link: ./index.html#data-cleaning-and-exploratory-data-analysis
    sublist:
      - name: Target variables
        link: ./index.html#calculation-of-target-variables
      - name: MIR TB vs MIR TB-HIV
        link: ./index.html#mir_tb-vs-mir_tb_hiv
      - name: CDR vs MIRs
        link: ./index.html#cdr-vs-mirs
      - name: Detection to Prevalence Ratio 
        link: ./index.html#detection-to-prevalence-ratio-(DPR)
  - name: Framing a Prediction Problem
    link: ./index.html#framing-a-prediction-problem
    sublist:
      - name: Problem Type
        link: ./index.html#problem-type
      - name: Features for Prediction
        link: ./index.html#features-for-prediction
      - name: Evaluation Metrics
        link: ./index.html#evaluation-metrics
  - name: Baseline Model
    link: ./index.html#baseline-model
    sublist:
      - name: MIR TB
        link: ./index.html#mir-tb
      - name: MIR TB-HIV
        link: ./index.html#mir-tb-hiv
  - name: Final Model
    link: ./index.html#final-model
    sublist:
      - name: Modeling Algorithm
        link: ./index.html#modeling-algorithm
      - name: New MIR TB
        link: ./index.html#new-mir-tb
      - name: New MIR TB-HIV
        link: ./index.html#new-mir-tb-hiv
  
             
  # - name: Data Retrieval and Parsing using Web Scraping and APIs
  #   link: ./index.html#data-retrieval-and-parsing-using-web-scraping-and-apis
  # - name: EDA and Visualizations Toolkit
  #   link: ./index.html#eda-and-visualizations-toolkit
  # - name: Travelling Salesman Problem
  #   link: ./index.html#travelling-salesman-problem
  # - name: Pixel Crafter
  #   link: ./index.html#pixel-crafter
